In [3]:
#loading the data
import pandas as pd
df = pd.read_csv("superstore_analysis.csv", encoding="ISO-8859-1")
df.drop(columns=['Column1'], inplace=True)
print(df.head())

         Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520
1  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520
2  CA-2016-138688   6/12/2016   6/16/2016    Second Class    DV-13045
3  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335
4  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335

     Customer Name    Segment        Country             City       State  \
0      Claire Gute   Consumer  United States        Henderson    Kentucky
1      Claire Gute   Consumer  United States        Henderson    Kentucky
2  Darrin Van Huff  Corporate  United States      Los Angeles  California
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida

   Postal Code Region       Product ID         Category Sub-Category  \
0        42420  South  FUR-BO-10001798        Furniture    Bookcases
1        42420  South  FUR-CH-10000454        Furniture       Chairs
2        90036   West  OFF-LA-10000240  Office Supplies       Labels
3        33311  South  FUR-TA-10000577        Furniture       Tables
4        33311  South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                     Eldon Fold 'N Roll Cart System   22.3680         2

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9994 non-null   object
 1   Order Date     9994 non-null   object
 2   Ship Date      9994 non-null   object
 3   Ship Mode      9994 non-null   object
 4   Customer ID    9994 non-null   object
 5   Customer Name  9994 non-null   object
 6   Segment        9994 non-null   object
 7   Country        9994 non-null   object
 8   City           9994 non-null   object
 9   State          9994 non-null   object
 10  Postal Code    9994 non-null   int64
 11  Region         9994 non-null   object
 12  Product ID     9994 non-null   object
 13  Category       9994 non-null   object
 14  Sub-Category   9994 non-null   object
 15  Product Name   9994 non-null   object
 16  Sales          9994 non-null   float64
 17  Quantity       9994 non-null   int64
 18  Discount       9994 non-null   float64
 19  Profit         9994 non-null   float64
dtypes: float64(3), int64(2), object(15)
memory usage: 1.5+ MB

In [5]:
df.describe()

        Postal Code         Sales     Quantity     Discount       Profit
count   9994.000000   9994.000000  9994.000000  9994.000000  9994.000000
mean   55190.379428    229.858001     3.789574     0.156203    28.656896
std    32063.693350    623.245101     2.225110     0.206452   234.260108
min     1040.000000      0.444000     1.000000     0.000000 -6599.978000
25%    23223.000000     17.280000     2.000000     0.000000     1.728750
50%    56430.500000     54.490000     3.000000     0.200000     8.666500
75%    90008.000000    209.940000     5.000000     0.200000    29.364000
max    99301.000000  22638.480000    14.000000     0.800000  8399.976000

In [6]:
#handling the missing values
df.isnull().sum()

Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [7]:
#cleaning the column names
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [8]:
print(df.head(10))

         order_id  order_date   ship_date       ship_mode customer_id  \
0  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520
1  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520
2  CA-2016-138688   6/12/2016   6/16/2016    Second Class    DV-13045
3  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335
4  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335
5  CA-2014-115812    6/9/2014   6/14/2014  Standard Class    BH-11710
6  CA-2014-115812    6/9/2014   6/14/2014  Standard Class    BH-11710
7  CA-2014-115812    6/9/2014   6/14/2014  Standard Class    BH-11710
8  CA-2014-115812    6/9/2014   6/14/2014  Standard Class    BH-11710
9  CA-2014-115812    6/9/2014   6/14/2014  Standard Class    BH-11710

     customer_name    segment        country             city       state  \
0      Claire Gute   Consumer  United States        Henderson    Kentucky
1      Claire Gute   Consumer  United States        Henderson    Kentucky
2  Darrin Van Huff  Corporate  United States      Los Angeles  California
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida
5  Brosina Hoffman   Consumer  United States      Los Angeles  California
6  Brosina Hoffman   Consumer  United States      Los Angeles  California
7  Brosina Hoffman   Consumer  United States      Los Angeles  California
8  Brosina Hoffman   Consumer  United States      Los Angeles  California
9  Brosina Hoffman   Consumer  United States      Los Angeles  California

   postal_code region       product_id         category sub-category  \
0        42420  South  FUR-BO-10001798        Furniture    Bookcases
1        42420  South  FUR-CH-10000454        Furniture       Chairs
2        90036   West  OFF-LA-10000240  Office Supplies       Labels
3        33311  South  FUR-TA-10000577        Furniture       Tables
4        33311  South  OFF-ST-10000760  Office Supplies      Storage
5        90032   West  FUR-FU-10001487        Furniture  Furnishings
6        90032   West  OFF-AR-10002833  Office Supplies          Art
7        90032   West  TEC-PH-10002275       Technology       Phones
8        90032   West  OFF-BI-10003910  Office Supplies      Binders
9        90032   West  OFF-AP-10002892  Office Supplies   Appliances

                                        product_name     sales  quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                     Eldon Fold 'N Roll Cart System   22.3680         2
5  Eldon Expressions Wood and Plastic Desk Access...   48.8600         7
6                                         Newell 322    7.2800         4
7                     Mitel 5320 IP Phone VoIP phone  907.1520         6
8  DXL Angle-View Binders with Locking Rings by S...   18.5040         3
9                   Belkin F5C206VTEL 6 Outlet Surge  114.9000         5

   discount    profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164
5      0.00   14.1694
6      0.00    1.9656
7      0.20   90.7152
8      0.20    5.7825
9      0.00   34.4700

In [9]:
#Changing the data types
df[['order_date','ship_date']] = df[['order_date','ship_date']].apply(pd.to_datetime, errors ="coerce")

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       9994 non-null   object
 1   order_date     9994 non-null   datetime64[ns]
 2   ship_date      9994 non-null   datetime64[ns]
 3   ship_mode      9994 non-null   object
 4   customer_id    9994 non-null   object
 5   customer_name  9994 non-null   object
 6   segment        9994 non-null   object
 7   country        9994 non-null   object
 8   city           9994 non-null   object
 9   state          9994 non-null   object
 10  postal_code    9994 non-null   int64
 11  region         9994 non-null   object
 12  product_id     9994 non-null   object
 13  category       9994 non-null   object
 14  sub-category   9994 non-null   object
 15  product_name   9994 non-null   object
 16  sales          9994 non-null   float64
 17  quantity       9994 non-null   int64
 18  discount       9994 non-null   float64
 19  profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(2), object(13)
memory usage: 1.5+ MB

In [11]:
#checking if their is any duplicate value in dataset
df.duplicated().any()

True

In [12]:
df.duplicated().sum()

1

In [13]:
df[df.duplicated(keep=False)]

,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,state,postal_code,region,product_id,category,sub-category,product_name,sales,quantity,discount,profit
3405,US-2014-150119,2014-04-23,2014-04-27,Standard Class,LB-16795,Laurel Beltran,Home Office,United States,Columbus,Ohio,43229,East,FUR-CH-10002965,Furniture,Chairs,Global Leather Highback Executive Chair with P...,281.372,2,0.3,-12.0588
3406,US-2014-150119,2014-04-23,2014-04-27,Standard Class,LB-16795,Laurel Beltran,Home Office,United States,Columbus,Ohio,43229,East,FUR-CH-10002965,Furniture,Chairs,Global Leather Highback Executive Chair with P...,281.372,2,0.3,-12.0588

In [14]:
#dropping the duplicate item
df = df.drop_duplicates()

In [15]:
df.duplicated().any()

False

In [16]:
df['year']=df['order_date'].dt.year
df['month']=df['order_date'].dt.month
df['month_name']=df['order_date'].dt.month_name()

In [17]:
df['profit_margin'] = df['profit'] / df['sales']

In [18]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,state,...,sub-category,product_name,sales,quantity,discount,profit,year,month,month_name,profit_margin
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,...,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,11,November,0.1600
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,11,November,0.3000
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,...,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016,6,June,0.4700
3,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,10,October,-0.4000
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,...,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,10,October,0.1125

In [49]:
#checking the outliers in the dataset
import numpy as np
q1 = df['sales'].quantile(0.25)
q3 = df['sales'].quantile(0.75)
iqr = q3 - q1
df['is_outlier'] = ((df['sales'] < (q1 - 1.5*iqr)) | (df['sales'] > (q3 + 1.5*iqr)))

In [50]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,state,...,product_name,sales,quantity,discount,profit,year,month,month_name,profit_margin,is_outlier
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,...,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136,2016,11,November,0.1600,False
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,...,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714,2016,6,June,0.4700,False
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,...,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164,2015,10,October,0.1125,False
5,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,...,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694,2014,6,June,0.2900,False
6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,...,Newell 322,7.280,4,0.0,1.9656,2014,6,June,0.2700,False

In [51]:
df.to_csv("cleaned_superstore.csv", index=False)

In [32]:
df.columns

Index(['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_id',
       'customer_name', 'segment', 'country', 'city', 'state', 'postal_code',
       'region', 'product_id', 'category', 'sub-category', 'product_name',
       'sales', 'quantity', 'discount', 'profit', 'year', 'month',
       'month_name', 'profit_margin', 'is_outlier'],
      dtype='object')

In [33]:
print(len(df.columns))

25

In [34]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\ankit dubey\anaconda3\lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\users\ankit dubey\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ankit dubey\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\ankit dubey\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Note: you may need to restart the kernel to use updated packages.

In [43]:
#Now connecting to PostgreSQL

username = "postgres"      # default user
password = "Ankit%40092005" # the password you set during installation
host = "localhost"         # if running locally
port = "5432"              # default PostgreSQL port
database = "ai_sales"    # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "sales"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'sales' in database 'ai_sales'.